### ISSUE TITLE
Does not start on a Mac

### ISSUE THREAD

**Issue by salomonderossi** [chaosbuffalolabs/ParticlePanda#4]
Hello,

I am running OS X 10.8.3 with kivy 0.7.1 and python 2.7.2. I installed the needed libraries as described in the README.md (at least I think so)...

When running ParticlePanda with the command:

``` bash
kivy main.py
```

I get the following error on the console:

```
...
[DEBUG  ] [ImageImageIO] Load <media/particle.png>
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "main.py", line 937, in <module>
     ParticleBuilderApp().run()
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/app.py", line 600, in run
     runTouchApp()
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/base.py", line 454, in runTouchApp
     EventLoop.window.mainloop()
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/core/window/window_pygame.py", line 325, in mainloop
     self._mainloop()
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/core/window/window_pygame.py", line 231, in _mainloop
     EventLoop.idle()
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/base.py", line 294, in idle
     Clock.tick()
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/clock.py", line 370, in tick
     self._process_events()
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/clock.py", line 481, in _process_events
     if event.tick(self._last_tick) is False:
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/clock.py", line 280, in tick
     ret = callback(self._dt)
   File "main.py", line 119, in load_default_particle
     self.load_particle()
   File "main.py", line 304, in load_particle
     pl.create_tabs()
   File "main.py", line 76, in create_tabs
     th3.content = ColorPanel(pbuilder)
   File "main.py", line 726, in __init__
     super(ColorPanel, self).__init__(**kwargs)
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/uix/widget.py", line 146, in __init__
     Builder.apply(self)
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/lang.py", line 1412, in apply
     self._apply_rule(widget, rule, rule)
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/lang.py", line 1517, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/lang.py", line 1517, in _apply_rule
     self._apply_rule(child, crule, rootrule)
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/lang.py", line 1516, in _apply_rule
     self.apply(child)
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/lang.py", line 1412, in apply
     self._apply_rule(widget, rule, rule)
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/lang.py", line 1465, in _apply_rule
     rule.canvas_root, rootrule)
   File "/Applications/Kivy.app/Contents/Resources/kivy/kivy/lang.py", line 1614, in _build_canvas
     raise BuilderException(prule.ctx, prule.line, str(e))
 kivy.lang.BuilderException: Parser: File "colorpicker/colorpicker.kv", line 8:
 ...
       6:    canvas:
       7:        Color:
 >>    8:            rgba: root.bg_color
       9:        Rectangle:
      10:            pos: root.pos
 ...
 Parser: File "colorpicker/colorpicker.kv", line 8:
 ...
       6:    canvas:
       7:        Color:
 >>    8:            rgba: root.bg_color
       9:        Rectangle:
      10:            pos: root.pos
 ...
 'ColorPicker' object has no attribute 'bg_color'
```

Maybe you can help me out here a little. At the moment I am trying to lern kivy and could not find any obvious errors.

King regards,
salomonderossi

**Comment by Kovak** [comment]
Hi,

I believe this is an issue with Kivy 1.7.0.

Particle Panda has not been updated yet for 1.7.0, I can confirm that it also does not work on my linux machine with 1.7.0 yet but it did work with 1.6.0. 

I will be gone for the next few days but I will be back next monday and try to get this resolved early in the week.

**Comment by salomonderossi** [comment]
Thank you for your fast reply. Do you know what the problem is with kivy 1.7.0? I am interested.
I am looking forward to your solution next week :smile:

**Comment by Kovak** [comment]
I think it has to do with the fact that colorpicker was included in the
kivy standard widget library starting with 1.7.0. It seems to me that the
ColorPicker rule in kv might be registering this new widget with slightly
different specifications rather than the original one we built for particle
panda. Although the colorpicker is based off the one from particle panda,
some details were changed and polished up. That's my first guess as to what
is going on.

**Comment by lietu** [comment]
Also confirming that this issue is present on Windows + Kivy 1.7.0

**Comment by Kovak** [comment]
Ok, this should work now. Our colorpicker was in conflict with the new default color picker that was put into Kivy. Changed the one in particle panda to be CBLColorPicker and it should work with 1.7.0 from now on. For those of you learning kivy, I would not recommend using our ColorPicker over the standard libraries new one, at the moment I just don't feel it is necessary to rework Particle Panda to use the standard library's (better) widget.

**Comment by lietu** [comment]
At least on Windows:

 Traceback (most recent call last):
   File "C:\source\ParticlePanda-master\main.py", line 16, in <module>
     from colorpicker.colorpicker import CBLColorPicker, CBLColorWheel
 ImportError: No module named colorpicker

**Comment by Kovak** [comment]
Thanks for the prompt response. I think changing that import to
from colorpicker.cblcolorpicker import CBLColorPicker, CBLColorWheel should fix it. I had a leftover .pyc that was hiding that error from me.  Is fixed in master now.

**Comment by lietu** [comment]
Excellent, now I'm able to run it on Windows .. however, only if I run it from command prompt with Kivy environment activated, as in:
c:\kivy-1.7.0\kivy
python main.py

.. it does not work with the Kivy recommended "Send to" -link for some reason, I get:

 Traceback (most recent call last):
   File "C:\source\ParticlePanda-master\main.py", line 930, in <module>
     Builder.load_file('colorpicker/cblcolorpicker.kv')
   File "C:\Kivy-1.7.0\kivy\kivy\lang.py", line 1298, in load_file
     with open(filename, 'r') as fd:
 IOError: [Errno 2] No such file or directory: 'colorpicker/cblcolorpicker.kv'

**Comment by Kovak** [comment]
I'm wondering if this is a bug with kivy's builder.load_file and Windows. It might be failing to get the correct path to cblcolorpicker.kv using the "send to" method. 

I don't have a Windows comp to test on but I think this might be how to fix it:

Will you test this small app for me: http://www.thehkstudio.com/send_to_method_test.zip

**Comment by lietu** [comment]
Sure, can test it later, just left for work.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by Kovak** [comment]
Thank you!

**Comment by lietu** [comment]
Ok, looks like for some reason when running stuff with the "Send To" -shortcut, the working directory is in the Kivy environment, not in the directory of the python script being run. As such, that script fails with this output: http://pastebin.com/gWH77qcq

But by changing line 6 to:
colorpickerkv_dir = os.path.dirname(**file**) + '/colorpicker/cblcolorpicker.kv'

.. it runs fine

**Comment by Kovak** [comment]
Ok I included this change in the master branch now too, hopefully it will work for you
